# Generated by Django 3.2.5 on 2021-12-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='action',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('yearly_leave', 'Yearly Leave')], max_length=30),
        ),
    ]
