# Generated by Django 3.2.3 on 2021-08-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyparticipent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circular_No', models.IntegerField()),
                ('Full_name', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=50)),
                ('Job_type', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('related_exprience', models.CharField(max_length=500)),
                ('job_reason', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='participent_profiles/')),
                ('cv', models.FileField(upload_to='participent_cv/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Participent',
        ),
        migrations.RenameField(
            model_name='circular',
            old_name='Job_title',
            new_name='job_title',
        ),
    ]
