# Generated by Django 3.2.5 on 2021-08-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOBs', '0002_auto_20210824_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyparticipent',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='applyparticipent',
            old_name='Job_title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='applyparticipent',
            old_name='Job_type',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='circular',
            old_name='Job_type',
            new_name='job_type',
        ),
    ]
