# Generated by Django 3.2.5 on 2021-08-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBs', '0003_auto_20210830_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyparticipent',
            name='action',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
