# Generated by Django 3.2.5 on 2021-11-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('possition', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('absent', models.CharField(max_length=100)),
                ('total_salary', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
    ]
