# Generated by Django 3.2.5 on 2021-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applying_traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Possition', models.CharField(max_length=100)),
                ('Course_name', models.CharField(max_length=100)),
                ('Applying_date', models.DateField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30)),
            ],
        ),
    ]
